In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = sns.load_dataset('titanic')

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [6]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [7]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [8]:
df['embarked'].isnull().sum()
df['embark_town'].isnull().sum()

np.int64(2)

In [9]:
df['embarked'].mode()
df['embark_town'].mode()

0    Southampton
Name: embark_town, dtype: object

In [10]:
df['embarked'].isnull().any()

np.True_

In [15]:
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])

In [16]:
df['age']=df['age'].fillna(df['age'].mean())

In [17]:
df=df.drop(columns=['deck'])

KeyError: "['deck'] not found in axis"

In [18]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [19]:
df['sex'] = df['sex'].astype('category')
df['embarked'] = df['embarked'].astype('category')
df['embark_town'] = df['embark_town'].astype('category')
df['alive'] = df['alive'].astype('category')

In [20]:
#normalization
df['fare'] = (df['fare'] - df['fare'].min()) / (df['fare'].max() - df['fare'].min())

In [21]:
df['fare']

0      0.014151
1      0.139136
2      0.015469
3      0.103644
4      0.015713
         ...
886    0.025374
887    0.058556
888    0.045771
889    0.058556
890    0.015127
Name: fare, Length: 891, dtype: float64

In [22]:
from sklearn.preprocessing import MinMaxScaler

In [23]:
scaler=MinMaxScaler()

In [25]:
df[['age']]=scaler.fit_transform(df[['age']])

In [26]:
# df['sex'] = df['sex'].map({'male': 0, 'female': 1})

In [27]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: sex, Length: 891, dtype: int64

In [29]:
df=pd.get_dummies(df,columns=['embarked'])

In [30]:
df

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,embark_town,alive,alone,embarked_C,embarked_Q,embarked_S
0,0,3,1,0.271174,1,0,0.014151,Third,man,True,Southampton,no,False,False,False,True
1,1,1,0,0.472229,1,0,0.139136,First,woman,False,Cherbourg,yes,False,True,False,False
2,1,3,0,0.321438,0,0,0.015469,Third,woman,False,Southampton,yes,True,False,False,True
3,1,1,0,0.434531,1,0,0.103644,First,woman,False,Southampton,yes,False,False,False,True
4,0,3,1,0.434531,0,0,0.015713,Third,man,True,Southampton,no,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,0.334004,0,0,0.025374,Second,man,True,Southampton,no,True,False,False,True
887,1,1,0,0.233476,0,0,0.058556,First,woman,False,Southampton,yes,True,False,False,True
888,0,3,0,0.367921,1,2,0.045771,Third,woman,False,Southampton,no,False,False,False,True
889,1,1,1,0.321438,0,0,0.058556,First,man,True,Cherbourg,yes,True,True,False,False
890,0,3,1,0.396833,0,0,0.015127,Third,man,True,Queenstown,no,True,False,True,False